Feature: Created view my flights
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-aug21-k05-t02 pull request #14
Opened 2021-09-29 18:15 UTC by 96vladi

# Description 
- My-flights view was implemented
- The following components were created with their own styles
    - BlockFlights: That stores all the data of each flight
   - FloatingB: It is the button to add more flights
   - Colors: Contains the colors that we are going to use in the development
- A defined list was created at the moment only for tests
- It was installed and made use of
react-native-vector-icons
- It does not have any functionality at the moment it is only a design
  
  ## Screenshots 
 
![image](https://user-images.githubusercontent.com/38408590/135324911-0537c02d-f54c-4cca-b5db-0abf5099e21d.png)

2021-09-29 18:40 UTC, LeyaimMagma requested changes
you forgot to add blanks in some files

2021-09-29 18:40 UTC, LeyaimMagma commented on src/components/floatingB/index.js
> +};
and blank space

2021-09-29 18:40 UTC, LeyaimMagma commented on src/components/floatingB/styledComponent.js
> +`;
add blank space

2021-09-29 18:40 UTC, LeyaimMagma commented on src/components/generals.js
> +`;
add blank space

2021-09-29 18:40 UTC, LeyaimMagma commented on src/screen/myFlights/index.js
> +export default MyFlights;
add blank space

2021-09-29 18:40 UTC, LeyaimMagma commented on src/screen/myFlights/styledComponent.js
> +`;
add blank space

2021-09-30 14:28 UTC, Shadic78 submitted a review, later dismissed

2021-09-30 15:20 UTC, DemisRincon approved these changes

2021-09-30 15:42 UTC, Shadic78 approved these changes

2021-09-30 15:45 UTC, EusebioAjas approved these changes

2021-09-30 16:39 UTC, jkzasori approved these changes

2021-09-30 18:43 UTC, LeyaimMagma approved these changes

2021-09-30 18:44 UTC, merged