Booking screens added
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-aug21-k05-t02 pull request #22
Opened 2021-10-05 17:19 UTC by ljau

# Description
What did you implemented/Why did you implemented this:
-Added Booking screens.
-Added navigation to those screens
-Corrected my flights screen
-Reorganized some components

2021-10-05 18:23 UTC, YilKanda requested changes

2021-10-05 18:23 UTC, YilKanda commented on .env
> +WEB_CLIENT=846077567519-lms5t9qj6ebt77r43cbapaq3c87t0m6a.apps.googleusercontent.com
This file dont upload to GitHub, you can use a example file.

2021-10-05 19:27 UTC, YilKanda approved these changes

2021-10-05 20:01 UTC, Shadic78 approved these changes

2021-10-05 20:05 UTC, merged

2021-10-06 02:27 UTC, YilKanda commented on .gitignore
> +.env
You only needed to add an example file, to identify how the key should be entered.