Fixed data register on firestore
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-aug21-k05-t02 pull request #36
Opened 2021-10-20 19:03 UTC by ljau

Registers properly new users and new added flights

Co-authored-by: 96vladi <maidana.vladi@gmail.com>

2021-10-20 19:09 UTC, DemisRincon requested changes
check the comments in general good

2021-10-20 19:09 UTC, DemisRincon commented on src/containers/BookingReceived/index.js
> +
remove console logs

2021-10-20 19:09 UTC, DemisRincon commented on src/containers/BookingReceived/index.js
> +      console.log("THIS IS THE RESPONSE", response.data())
remove console logs

2021-10-20 19:09 UTC, DemisRincon commented on src/library/methods/auth.js
> +
remove console log

2021-10-20 19:13 UTC, ljau commented on src/containers/BookingReceived/index.js
> +
logs removed

2021-10-20 19:13 UTC, ljau commented on src/containers/BookingReceived/index.js
> +      console.log("THIS IS THE RESPONSE", response.data())
logs removed

2021-10-20 19:13 UTC, ljau commented on src/library/methods/auth.js
> +
logs removed

2021-10-20 21:57 UTC, RaulMorales404 approved these changes

2021-10-21 14:36 UTC, Shadic78 approved these changes
Good

2021-10-21 14:44 UTC, DemisRincon approved these changes

2021-10-21 14:45 UTC, merged